version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 olms.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/olmspythondb
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=0.0.0.0

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: olmspythondb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

